// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// BEGINNER NOTE:
// [DefaultFirebaseOptions] contains platform-specific Firebase configuration keys
// (API keys, project ID, messaging sender ID, storage bucket).
// When the app starts up in `main.dart`, `Firebase.initializeApp(...)` calls
// `DefaultFirebaseOptions.currentPlatform` to select the right configuration for
// Android, iOS, or Web without manual platform branching in app code.
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiqXdkok8p84jUTYKA92eleqpJt4U5i00',
    appId: '1:720004989036:web:89c7f8865549ef3c4c9849',
    messagingSenderId: '720004989036',
    projectId: 'paperroutedev',
    authDomain: 'paperroutedev.firebaseapp.com',
    storageBucket: 'paperroutedev.firebasestorage.app',
    measurementId: 'G-7ZNCJYGLT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuPsUbxwZLfs_2CyDI2jE8NMAdU-_t0Y',
    appId: '1:720004989036:android:e7140626772487fd4c9849',
    messagingSenderId: '720004989036',
    projectId: 'paperroutedev',
    storageBucket: 'paperroutedev.firebasestorage.app',
  );
}
